### PR TITLE
Added automatic user detection

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by dicexq** [comment]
Tested this commit on an existing SF 3.1.4 project, works fine.

**Comment by GrahamCampbell** [comment]
Awesome. :)

**Comment by GrahamCampbell** [comment]
Friendly ping @kattrali. :)

**Comment by kattrali** [comment]
Thanks for the ping, @GrahamCampbell. I sometimes have my hands full. :)

**Pull request merged**
