### PR TITLE
support notify_hostnames config.yml node

### PR DESCRIPTION
**Pull request by janmyszkier**
requires: https://github.com/bugsnag/bugsnag-php/pull/410 to be part of bugsnag-php to work as intended

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks. We'll also need to add the equivalent for the laravel/silex notifiers. :)

**Comment by janmyszkier** [comment]
@GrahamCampbell : Sorry, not having enough laravel/silex apps here to consider any "best practice" and provide sample implementation for those. Do you still want me to try deliver what I think will work? Or you can handle this on your own?

**Comment by Cawllec** [comment]
Hi @janmyszkier, see my comment on your [parent PR](https://github.com/bugsnag/bugsnag-php/pull/410)

**Comment by janmyszkier** [comment]
@Cawllec thank you, but didn't help. see my answer

**Pull request closed without merging**
