### PR TITLE
[WIP] Release 1.1.0

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Needs updating following https://github.com/bugsnag/bugsnag-symfony/pull/31.

**Comment by GrahamCampbell** [comment]
Just updated this. Dated the release for tomorrow. Don't know what the actual release plans are. :)

**Comment by dicexq** [comment]
The master seems stable for a while, 
Can there be a new release with the latest changes?
I prefer version over dev-master requirements.

**Comment by GrahamCampbell** [comment]
You can still use 1.1.x without having to use `dev-master`, due to the branch alias. `^1.1@dev` should resolve the new version, for example.

**Comment by GrahamCampbell** [comment]
@kattrali Date looks wrong.

**Pull request merged**
