### PR TITLE
add notify except

### PR DESCRIPTION
**Pull request by roboticsexpert**
Add feature to add some exception to config for not reporting to bugsnag

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is already a supported feature, via registering filters.

**Comment by GrahamCampbell** [comment]
This is being made easier in https://github.com/bugsnag/bugsnag-symfony/pull/36 too.

**Comment by GrahamCampbell** [comment]
If we were to implement this feature, it would have to be implemented itself as a "callback", rather than being mushed into the code.

**Comment by roboticsexpert** [comment]
i really don't understand how can filter some exception type with callback but i think your idea should be better than me ... 

my problem was bandwidth of reporting exceptions to bugsnag that have very large impact on our limit (about 600mb every day), so for that i implement easiest way ...

but if possible to present some example code for your solution , i will appreciate you ...

**Comment by GrahamCampbell** [comment]
You can implement this in your app using callbacks, and there's no need for any changes to this package. Please see the docs at https://docs.bugsnag.com/platforms/php/symfony/configuration-options/#callbacks.

You can programmatically skip notifying:

```php
$this->get('bugsnag')->registerCallback(function ($report) {
    if ($report->getName() === 'Foo\Bar\Exception') {
        return false;
    }
});
```

**Comment by GrahamCampbell** [comment]
What I was saying that if we were to add this feature natively to this package, then it wouldn't need modifications like this. All we'd do is provide a callback that registers from the config file automatically if excluded exceptions are provided.

**Comment by roboticsexpert** [comment]
thank alot ... i fully understood ....

finally, want you add this feature to this package (if i implement that as you say) or not ?

**Pull request closed without merging**
