### PR TITLE
Symfony 4 support

### PR DESCRIPTION
**Pull request by Cawllec**
Adds support for and an example of Symfony 4.

Note: While the library itself doesn't need updating, the methods of using services has changed with Symfony 4, and the docs will require thought put in to how to reflect this.

For now the example README contains an updated guide on integration.

### CODE REVIEW

**Comment by bitecodes** [comment]
I have the feeling this currently does not work well with Symfony Flex. I created my Symfony 4 application with Flex and this will create a composer.json file that defines
```
"conflict": {
  "symfony/symfony": "*"
}
```
Now as this package requires `"symfony/symfony": "^2.7|^3.0|^4.0"` the install will fail with
```
...
- symfony/symfony v4.0.1 conflicts with __root__[dev-master].
- symfony/symfony v4.0.2 conflicts with __root__[dev-master].
- Installation request for __root__ dev-master -> satisfiable by __root__[dev-master].
- Installation request for bugsnag/bugsnag-symfony dev-cawllec/symfony-4 -> satisfiable by bugsnag/bugsnag-symfony[dev-cawllec/symfony-4].
```
I guess, this package should now depend on the required components `symfony/dependency-injection`, `symfony/http-kernel` and `symfony/event-dispatcher` (anything else?) instead.

**Comment by Cawllec** [comment]
Ok, I'm not sure if this will break backwards compatibility with older symfony versions.  If so we'll need to discuss how to best deal with it.

**Comment by bitecodes** [comment]
From my understanding, requiring `symfony/symfony` will install all Symfony components and the standalone components are just subtree splits of the main repository. So I would assume that specifying single components should be fine as the package would now just depend on a subset of the components instead of requiring them all.

I also had a look at other popular packages and that seems like what everyone else is doing.

**Comment by bitecodes** [comment]
I don't think a 1.x branch and a bump to 2.0 would even be necessary. Relying on the specific components instead of the whole framework should not cause any backwards compatibility issues, imo.

**Comment by GrahamCampbell** [comment]
Surely there's a way we just depend on the specific components this packages uses, instead of on symfony/symfony, thus solving everything in a BC way.

**Comment by Cawllec** [comment]
Ok, I've defined the specific components required and tested across 2.7, 2.8, 3.1 & 4.0 and with a few adjustments to 4.0 everything is working well.

**Comment by GrahamCampbell** [comment]
I'll take a look at this in the next 48 hours. :)

**Comment by GrahamCampbell** [comment]
Yeh, looks good. 👍

**Pull request merged**
